/**
 * Sistema de clasificación temática del chatbot
 * Keywords organizados por categoría para clasificar las preguntas del usuario
 */

export const CATEGORY_KEYWORDS = {
  incapacidades: [
    "incapacidad",
    "incapacidades",
    "licencia médica",
    "licencias",
    "pago incapacidad",
    "eps",
    "arl",
    "compensar",
    "nueva eps",
    "famisanar",
    "sanitas",
    "sura",
    "medicina laboral",
    "ausentismo",
    "certificado médico",
    "reposo",
    "baja médica",
    "invalidez",
    "discapacidad",
    "rehabilitación",
    "accidente trabajo",
    "enfermedad profesional",
  ],
  compensacion_final: [
    "compensación final",
    "compensacion final",
    "liquidación",
    "liquidaciones",
    "liquidación pendiente",
    "documentos pendientes",
    "convenios pendientes",
    "carta de retiro",
    "acta de entendimiento",
    "acta de compromiso",
    "solicitud afiliación",
    "estado compensación",
    "proceso compensación",
    "retiro sindical",
    "documentación retiro",
    "pendientes retiro",
  ],
  certificados: [
    "certificado",
    "certificados",
    "constancia",
    "constancias",
    "afiliación",
    "afiliaciones",
    "convenio sindical",
    "membresía",
    "carnet",
    "credencial",
    "acreditación",
    "documento",
    "comprobante",
    "paz y salvo",
    "solvencia",
    "vigencia",
    "certificación laboral",
    "certificado trabajo",
    "certificado sindical",
  ],
  contacto: [
    "teléfono",
    "teléfonos",
    "correo",
    "correos",
    "contacto",
    "contactar",
    "comunicar",
    "email",
    "dirección",
    "direcciones",
    "sede",
    "sedes",
    "oficina",
    "oficinas",
    "atención",
    "servicio al cliente",
    "pqr",
    "queja",
    "reclamo",
    "sugerencia",
    "horario",
    "horarios",
    "whatsapp",
    "chat",
    "llamar",
    "ubicación",
  ],
  convenios: [
    "convenio",
    "convenios",
    "acuerdo",
    "acuerdos",
    "alianza",
    "alianzas",
    "descuento",
    "descuentos",
    "beneficio",
    "beneficios",
    "promoción",
    "promociones",
    "oferta",
    "ofertas",
    "farmacia",
    "farmacias",
    "droguería",
    "droguerías",
    "clínica",
    "clínicas",
    "hospital",
    "hospitales",
    "laboratorio",
    "laboratorios",
    "consultorio",
    "consultorios",
    "odontología",
    "medicina general",
    "especialista",
    "especialistas",
  ],
  servicios: [
    "servicio",
    "servicios",
    "trámite",
    "trámites",
    "solicitud",
    "solicitudes",
    "proceso",
    "procesos",
    "procedimiento",
    "procedimientos",
    "requisito",
    "requisitos",
    "documento",
    "documentos",
    "formato",
    "formatos",
    "formulario",
    "formularios",
    "actualizar",
    "actualización",
    "cuenta bancaria",
    "datos",
    "información personal",
    "retiro",
    "descanso",
    "vacaciones",
    "permisos",
    "compensación",
    "crédito",
    "préstamo",
  ],
  normatividad: [
    "norma",
    "normas",
    "resolución",
    "resoluciones",
    "ley",
    "leyes",
    "decreto",
    "decretos",
    "reglamento",
    "reglamentos",
    "estatuto",
    "estatutos",
    "manual",
    "manuales",
    "política",
    "políticas",
    "procedimiento",
    "procedimientos",
    "lineamiento",
    "lineamientos",
    "jurídico",
    "legal",
    "derecho",
    "derechos",
    "obligación",
    "obligaciones",
    "contrato",
    "contratos",
    "sindical",
    "sindicato",
    "trabajador",
    "trabajadores",
  ],
  bienestar: [
    "bienestar",
    "actividad",
    "actividades",
    "recreación",
    "recreativa",
    "evento",
    "eventos",
    "celebración",
    "celebraciones",
    "deporte",
    "deportes",
    "cultura",
    "cultural",
    "taller",
    "talleres",
    "capacitación",
    "capacitaciones",
    "formación",
    "educación",
    "salud mental",
    "bienestar social",
    "integración",
    "convivencia",
  ],
  sst: [
    "sst",
    "seguridad",
    "salud ocupacional",
    "riesgo",
    "riesgos",
    "prevención",
    "accidente",
    "accidentes",
    "enfermedad",
    "enfermedades",
    "laboral",
    "ocupacional",
    "ergonomía",
    "higiene",
    "industrial",
    "protección",
    "elementos protección",
    "epp",
    "copasst",
    "comité",
    "seguridad industrial",
    "medicina preventiva",
  ],
};

// Indicadores de preguntas de seguimiento
export const FOLLOW_UP_INDICATORS = [
  "y también",
  "además",
  "adicionalmente",
  "otra cosa",
  "otra pregunta",
  "y qué",
  "y cuál",
  "y cómo",
  "y dónde",
  "y cuándo",
  "y quién",
  "y por qué",
  "también",
  "igualmente",
  "asimismo",
  "del mismo modo",
  "de igual manera",
  "y el",
  "y la",
  "y los",
  "y las",
  "respecto a",
  "acerca de",
  "relacionado con",
  "sobre eso",
  "sobre esto",
];

// Palabras contextuales que indican referencia a mensajes previos
export const CONTEXTUAL_WORDS = [
  "esto",
  "eso",
  "lo anterior",
  "lo que dijiste",
  "la información",
];

export type CategoryType =
  | "incapacidades"
  | "compensacion_final"
  | "certificados"
  | "contacto"
  | "convenios"
  | "servicios"
  | "normatividad"
  | "bienestar"
  | "sst"
  | "general";

