// Opciones para el formulario de actualización de datos personales

export const estadosCiviles = [
  { value: 'soltero', label: 'Soltero(a)' },
  { value: 'casado', label: 'Casado(a)' },
  { value: 'union_libre', label: 'Unión Libre' },
  { value: 'divorciado', label: 'Divorciado(a)' },
  { value: 'viudo', label: 'Viudo(a)' },
];

export const municipios = [
  { value: 'abejorral', label: 'Abejorral' },
  { value: 'abriaqui', label: 'Abriaquí' },
  { value: 'alejandria', label: 'Alejandría' },
  { value: 'amaga', label: 'Amagá' },
  { value: 'amalfi', label: 'Amalfi' },
  { value: 'andes', label: 'Andes' },
  { value: 'angelopolis', label: 'Angelópolis' },
  { value: 'angostura', label: 'Angostura' },
  { value: 'anori', label: 'Anorí' },
  { value: 'antequera', label: 'Antequera' },
  { value: 'apartado', label: 'Apartadó' },
  { value: 'arboletes', label: 'Arboletes' },
  { value: 'argelia', label: 'Argelia' },
  { value: 'armenia', label: 'Armenia' },
  { value: 'barbosa', label: 'Barbosa' },
  { value: 'bello', label: 'Bello' },
  { value: 'belmira', label: 'Belmira' },
  { value: 'betania', label: 'Betania' },
  { value: 'betulia', label: 'Betulia' },
  { value: 'briceño', label: 'Briceño' },
  { value: 'buritica', label: 'Buriticá' },
  { value: 'caceres', label: 'Cáceres' },
  { value: 'caicedo', label: 'Caicedo' },
  { value: 'caldas', label: 'Caldas' },
  { value: 'campamento', label: 'Campamento' },
  { value: 'canasgordas', label: 'Cañasgordas' },
  { value: 'caracoli', label: 'Caracolí' },
  { value: 'caramanta', label: 'Caramanta' },
  { value: 'carepa', label: 'Carepa' },
  { value: 'carolina', label: 'Carolina' },
  { value: 'caucasia', label: 'Caucasia' },
  { value: 'chigorodo', label: 'Chigorodó' },
  { value: 'cisneros', label: 'Cisneros' },
  { value: 'ciudad_bolivar', label: 'Ciudad Bolívar' },
  { value: 'cocorna', label: 'Cocorná' },
  { value: 'concepcion', label: 'Concepción' },
  { value: 'concordia', label: 'Concordia' },
  { value: 'copacabana', label: 'Copacabana' },
  { value: 'dabeiba', label: 'Dabeiba' },
  { value: 'don_matias', label: 'Don Matías' },
  { value: 'ebejico', label: 'Ebéjico' },
  { value: 'el_bagre', label: 'El Bagre' },
  { value: 'el_carmen', label: 'El Carmen de Viboral' },
  { value: 'el_santuario', label: 'El Santuario' },
  { value: 'entrerrios', label: 'Entrerríos' },
  { value: 'envigado', label: 'Envigado' },
  { value: 'fredonia', label: 'Fredonia' },
  { value: 'frontino', label: 'Frontino' },
  { value: 'giraldo', label: 'Giraldo' },
  { value: 'girardota', label: 'Girardota' },
  { value: 'gomez_plata', label: 'Gómez Plata' },
  { value: 'granada', label: 'Granada' },
  { value: 'guadalupe', label: 'Guadalupe' },
  { value: 'guarne', label: 'Guarne' },
  { value: 'guatape', label: 'Guatapé' },
  { value: 'heliconia', label: 'Heliconia' },
  { value: 'hispania', label: 'Hispania' },
  { value: 'itagui', label: 'Itagüí' },
  { value: 'ituango', label: 'Ituango' },
  { value: 'jardin', label: 'Jardín' },
  { value: 'jerico', label: 'Jericó' },
  { value: 'la_ceja', label: 'La Ceja' },
  { value: 'la_estrella', label: 'La Estrella' },
  { value: 'la_pintada', label: 'La Pintada' },
  { value: 'la_union', label: 'La Unión' },
  { value: 'liborina', label: 'Liborina' },
  { value: 'maceo', label: 'Maceo' },
  { value: 'marinilla', label: 'Marinilla' },
  { value: 'medellin', label: 'Medellín' },
  { value: 'montebello', label: 'Montebello' },
  { value: 'murindo', label: 'Murindó' },
  { value: 'mutata', label: 'Mutatá' },
  { value: 'narino', label: 'Nariño' },
  { value: 'nechi', label: 'Nechí' },
  { value: 'necocli', label: 'Necoclí' },
  { value: 'olaya', label: 'Olaya' },
  { value: 'peque', label: 'Peque' },
  { value: 'peñol', label: 'Peñol' },
  { value: 'pueblorrico', label: 'Pueblorrico' },
  { value: 'puerto_berrio', label: 'Puerto Berrío' },
  { value: 'puerto_nare', label: 'Puerto Nare' },
  { value: 'puerto_triunfo', label: 'Puerto Triunfo' },
  { value: 'remedios', label: 'Remedios' },
  { value: 'retiro', label: 'El Retiro' },
  { value: 'rionegro', label: 'Rionegro' },
  { value: 'sabanalarga', label: 'Sabanalarga' },
  { value: 'sabaneta', label: 'Sabaneta' },
  { value: 'salgar', label: 'Salgar' },
  { value: 'san_andres', label: 'San Andrés de Cuerquia' },
  { value: 'san_carlos', label: 'San Carlos' },
  { value: 'san_francisco', label: 'San Francisco' },
  { value: 'san_jeronymo', label: 'San Jerónimo' },
  { value: 'san_jose', label: 'San José de la Montaña' },
  { value: 'san_juan', label: 'San Juan de Urabá' },
  { value: 'san_luis', label: 'San Luis' },
  { value: 'san_pedro', label: 'San Pedro de los Milagros' },
  { value: 'san_pedro_uraba', label: 'San Pedro de Urabá' },
  { value: 'san_rafael', label: 'San Rafael' },
  { value: 'san_roque', label: 'San Roque' },
  { value: 'san_vicente', label: 'San Vicente' },
  { value: 'santa_barbara', label: 'Santa Bárbara' },
  { value: 'santa_fe', label: 'Santa Fe de Antioquia' },
  { value: 'santa_rosa', label: 'Santa Rosa de Osos' },
  { value: 'santo_domingo', label: 'Santo Domingo' },
  { value: 'santuario', label: 'El Santuario' },
  { value: 'segovia', label: 'Segovia' },
  { value: 'sonson', label: 'Sonsón' },
  { value: 'sopetran', label: 'Sopetrán' },
  { value: 'tamesis', label: 'Támesis' },
  { value: 'taraza', label: 'Tarazá' },
  { value: 'tarso', label: 'Tarso' },
  { value: 'titiribi', label: 'Titiribí' },
  { value: 'toledo', label: 'Toledo' },
  { value: 'turbo', label: 'Turbo' },
  { value: 'uramita', label: 'Uramita' },
  { value: 'urrao', label: 'Urrao' },
  { value: 'valdivia', label: 'Valdivia' },
  { value: 'valparaiso', label: 'Valparaíso' },
  { value: 'vegachi', label: 'Vegachí' },
  { value: 'venecia', label: 'Venecia' },
  { value: 'vigia_del_fuerte', label: 'Vigía del Fuerte' },
  { value: 'yali', label: 'Yalí' },
  { value: 'yarumal', label: 'Yarumal' },
  { value: 'yolombo', label: 'Yolombó' },
  { value: 'yondo', label: 'Yondó' },
  { value: 'zaragoza', label: 'Zaragoza' },
];

export const tallasUniforme = [
  { value: 'xs', label: 'XS - Extra Pequeña' },
  { value: 's', label: 'S - Pequeña' },
  { value: 'm', label: 'M - Mediana' },
  { value: 'l', label: 'L - Grande' },
  { value: 'xl', label: 'XL - Extra Grande' },
  { value: 'xxl', label: 'XXL - Extra Extra Grande' },
  { value: 'xxxl', label: 'XXXL - Triple Extra Grande' },
  { value: '4xl', label: '4XL - Cuatro Extra Grande' },
  { value: '5xl', label: '5XL - Cinco Extra Grande' },
];

export const nivelesEducativos = [
  { value: 'primaria', label: 'Primaria' },
  { value: 'bachiller', label: 'Bachiller' },
  { value: 'tecnico', label: 'Tecnico' },
  { value: 'tecnologo', label: 'Tecnologo' },
  { value: 'profesional', label: 'Profesional' },
  { value: 'especialista', label: 'Especialista' },
  { value: 'maestria', label: 'Maestría' },
  { value: 'doctorado', label: 'Doctorado' },
];

export const tiposCuenta = [
  { value: 'ahorros', label: 'Cuenta de Ahorros' },
  { value: 'corriente', label: 'Cuenta Corriente' },
];

export const bancos = [
  { value: 'bancolombia', label: 'Bancolombia' },
  { value: 'davivienda', label: 'Davivienda' },
  { value: 'bbva', label: 'BBVA' },
  { value: 'bogota', label: 'Banco de Bogotá' },
  { value: 'occidente', label: 'Banco de Occidente' },
  { value: 'popular', label: 'Banco Popular' },
  { value: 'av_villas', label: 'AV Villas' },
  { value: 'caja_social', label: 'Banco Caja Social' },
  { value: 'colpatria', label: 'Banco Colpatria' },
  { value: 'agrario', label: 'Banco Agrario' },
  { value: 'cooperativo', label: 'Banco Cooperativo Coopcentral' },
  { value: 'nequi', label: 'Nequi' },
  { value: 'otros', label: 'Otros' },
];

export { epsList } from '@/utils/epsNormalization';

export { afpList } from '@/utils/afpNormalization';

export const parentescos = [
  { value: 'MADRE', label: 'Madre' },
  { value: 'PADRE', label: 'Padre' },
  { value: 'HIJA', label: 'Hija' },
  { value: 'HIJO', label: 'Hijo' },
  { value: 'CONYUGUE', label: 'Cónyuge' },
  { value: 'HIJO_CONYUGUE', label: 'Hijo cónyuge' },
  { value: 'HIJA_CONYUGUE', label: 'Hija cónyuge' },
];

export const relacionesContactoEmergencia = [
  { value: 'conyuge', label: 'Cónyuge' },
  { value: 'padre', label: 'Padre' },
  { value: 'madre', label: 'Madre' },
  { value: 'hijo', label: 'Hijo/a' },
  { value: 'hermano', label: 'Hermano/a' },
  { value: 'abuelo', label: 'Abuelo/a' },
  { value: 'tio', label: 'Tío/a' },
  { value: 'primo', label: 'Primo/a' },
  { value: 'amigo', label: 'Amigo/a' },
  { value: 'otro', label: 'Otro' },
];

export const tiposDocumento = [
  { value: 'CC', label: 'CC' },
  { value: 'TI', label: 'TI' },
  { value: 'CE', label: 'CE' },
  { value: 'PA', label: 'PA' },
  { value: 'RC', label: 'RC' },
  { value: 'PT', label: 'PT' },
];

export const tiposDocumentoCompletos = [
  { value: 'CC', label: 'Cédula de Ciudadanía' },
  { value: 'TI', label: 'Tarjeta de Identidad' },
  { value: 'CE', label: 'Cédula de Extranjería' },
  { value: 'PA', label: 'Pasaporte' },
  { value: 'RC', label: 'Registro Civil' },
  { value: 'PT', label: 'Permiso por Protección Temporal' },
];

/** Tipos de documento permitidos en encuestas (sociodemográfica y vacunación). Sin TI. */
export const tiposDocumentoEncuestas = [
  { value: 'CC', label: 'Cédula de Ciudadanía (CC)' },
  { value: 'CE', label: 'Cédula de Extranjería (CE)' },
  { value: 'PT', label: 'Permiso por Protección Temporal (PT)' },
];

